<?php
// auto generated by RMS setup
class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'rms',
		'password' => 'YmJhNGE0YTFiMzI4',
		'database' => 'rms',
		'encoding' => 'utf8'
	);
}
